- custom_components/unfoldedcircle/switch.py
Set switch state immediately after calling into api to maintain correct state in ui
> Improve Switch State Handling

- custom_components/unfoldedcircle/manifest.json
> Bump manifest

- README.md
- custom_components/unfoldedcircle/__init__.py
- custom_components/unfoldedcircle/binary_sensor.py
- custom_components/unfoldedcircle/button.py
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/const.py
- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/remote.py
- custom_components/unfoldedcircle/sensor.py
- custom_components/unfoldedcircle/strings.json
- custom_components/unfoldedcircle/switch.py
- custom_components/unfoldedcircle/translations/en.json
- custom_components/unfoldedcircle/update.py
Your remote two will now be automatically discovered on the network. You can ignore this discovery if you have previously added your remote two to home assistant.
> Add Support for Zeroconf Discovery

- README.md
Added readme badges for the unfolded circle discord server, release version, and number of downloads
> Add Readme Badges

- custom_components/unfoldedcircle/media_player.py
The media position was not updated correctly because of the wrong timezone in the calculated date
> Fixed media position not updated

- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/media_player.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/const.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/remote.py
- custom_components/unfoldedcircle/update.py
This change adds support for three software update features within home assistant:
1. Installing software
2. Showing the software install progress
3. Displaying the software update release notes
> Software Update Support

- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/media_player.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/remote.py
- custom_components/unfoldedcircle/translations/en.json
- Map Media Player volume up, down, mute, next, previous, and play/pause to associated entity defined in your activity's button mapping
- This change makes your media players predicable and allows you to generically control your playing media based on the active activity
- Report Media Player as "on" if associated activity is running
- Always display available entities in Sound Mode dropdown as long as they are not "unavailable"
- Correctly report if media player unmutes
> Improve-media-player-support

- custom_components/unfoldedcircle/__init__.py
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/coordinator.py
- custom_components/unfoldedcircle/media_player.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/remote.py
- custom_components/unfoldedcircle/select.py
- custom_components/unfoldedcircle/switch.py
- custom_components/unfoldedcircle/update.py
Hi,
I have added support for the volume slider in media player entity
As before, I had to replace all the imports "from pyUnfoldedCircleRemote" by "from .pyUnfoldedCircleRemote" to make it work with the local library files.
> Added support for volume slider on media player entity

- custom_components/unfoldedcircle/__init__.py
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/coordinator.py
- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/media_player.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/remote.py
- custom_components/unfoldedcircle/select.py
- custom_components/unfoldedcircle/switch.py
- custom_components/unfoldedcircle/update.py
Corrects minor issues with previous pull request
Reverts to external remote module
> Volume set support

- custom_components/unfoldedcircle/__init__.py
- custom_components/unfoldedcircle/button.py
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/coordinator.py
- custom_components/unfoldedcircle/media_player.py
- custom_components/unfoldedcircle/number.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/dock.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/dock_websocket.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/websocket.py
- custom_components/unfoldedcircle/remote.py
- custom_components/unfoldedcircle/select.py
- custom_components/unfoldedcircle/sensor.py
- custom_components/unfoldedcircle/strings.json
- custom_components/unfoldedcircle/switch.py
- custom_components/unfoldedcircle/translations/en.json
- custom_components/unfoldedcircle/update.py
- requirements.txt
Adds support for adding a single dock to the integration
Limitation is currently in config flow
user input is not validated
> Dock-support

- README.md
- custom_components/unfoldedcircle/__init__.py
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/helpers.py
- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/dock_websocket.py
- custom_components/unfoldedcircle/repairs.py
- custom_components/unfoldedcircle/sensor.py
- custom_components/unfoldedcircle/translations/en.json
Adds support for controlling your Unfolded Circle Docks from within home assistant. Docks have a dependency on the remote.
> Dock Support

- custom_components/unfoldedcircle/coordinator.py
- custom_components/unfoldedcircle/websocket.py
I haved added the missing part to make custom events work.
I have tested with both old HA driver (with no custom events) and the last one from the beta version.
> Fix for custom events (replacing massive standard events)

- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/manifest.json
Fixes duplicate zeroconf discoveries by removing appended data to mac address
Fixes reported WOL bug by bumping dependency version
> Zeroconf and WOL bug fixes

- custom_components/unfoldedcircle/__init__.py
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/const.py
- custom_components/unfoldedcircle/coordinator.py
- custom_components/unfoldedcircle/icons.json
- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/dock_websocket.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/remote.py
- custom_components/unfoldedcircle/remote.py
- custom_components/unfoldedcircle/services.yaml
Adds the ability to send predefined IR codes from codesets supplied with the remote
> IR improvements

- custom_components/unfoldedcircle/__init__.py
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/helpers.py
- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/remote.py
- custom_components/unfoldedcircle/translations/en.json
* Adds ability to update ws url
* Improved upgrade state handling
> Improve Unified Integration

- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/remote.py
- custom_components/unfoldedcircle/translations/en.json
- custom_components/unfoldedcircle/translations/fr.json
Last modification : added a link at the selection step of entities
> Available mode

- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/update.py
Quick fix for config flow when adding entities to the remote
Improve update handling
> Config flow fix + update fix

- custom_components/unfoldedcircle/__init__.py
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/repairs.py
- custom_components/unfoldedcircle/translations/en.json
1. Add step to update remote host 
2. Add repair if user has not yet setup new connection logic
> Implement reconnect logic in reconfigure flow

- README.md
- custom_components/unfoldedcircle/config_flow.py
- custom_components/unfoldedcircle/const.py
- custom_components/unfoldedcircle/entity.py
- custom_components/unfoldedcircle/helpers.py
- custom_components/unfoldedcircle/icons.json
- custom_components/unfoldedcircle/manifest.json
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/dock.py
- custom_components/unfoldedcircle/pyUnfoldedCircleRemote/remote.py
- custom_components/unfoldedcircle/remote.py
- custom_components/unfoldedcircle/services.yaml
- custom_components/unfoldedcircle/switch.py
- custom_components/unfoldedcircle/update.py
- hacs.json
zeroconf 2025.2
send mapped buttons commands
Initial dock update support (only notification and install)
Fix bug where partial firmware progress was being reported
> Add initial support for dock firmware and sending mapped buton commands

- custom_components/unfoldedcircle/number.py
- custom_components/unfoldedcircle/update.py
Correctly send dock command as string to api rather than int
Handle dock update check failures
> Dock firmware
